wkillerud/some-sass

.editorconfig
.github/workflows/pull_request.yml
.vscode/settings.json
README.md
fixtures/e2e/.vscode/settings.json
fixtures/e2e/references/_dev.scss
fixtures/e2e/references/_fun.scss
fixtures/e2e/references/_one.scss
package-lock.json
package.json
src/unsafe/document.ts
src/unsafe/providers/completion/completion.ts
src/unsafe/providers/goDefinition.ts
src/unsafe/providers/hover.ts
src/unsafe/providers/references/index.ts
src/unsafe/providers/references/references.ts
src/unsafe/providers/signatureHelp.ts
src/unsafe/server.ts
src/unsafe/services/scanner.ts
src/unsafe/test/providers/goDefinition.spec.ts
src/unsafe/test/providers/references.spec.ts
src/unsafe/test/services/scanner.spec.ts
src/unsafe/test/utils/string.spec.ts
src/unsafe/types/symbols.ts
src/unsafe/types/tokens.ts
src/unsafe/utils/document.ts
src/unsafe/utils/fs.ts
src/unsafe/utils/string.ts

- Find all references to variables, mixins and functions.
- Find all references to Sass built-in functions and variables.
- For mixins with `@content` SassDoc annotation, add and prefer a suggestion without brackets. The one with brackets now needs an Arrow Down keypress to use.
- Don't give signature help for CSS functions with the same name, for instance `scale()`.
- Don't give hover information for CSS functions with the same name, for instance `scale()`.
- Fix default exclude patterns so they work as expected when used with `micromatch`.

feature: find all references

---

src/server/features/completion/completion.ts
src/server/features/completion/variable-completion.ts
src/server/features/go-definition/go-definition.ts
src/server/features/hover/hover.ts
src/server/utils/scss.ts

For completions and hover info, try to look for the base value if a variable is just a reference to another variable.
For completions this for instance means you can get color previews for semantic names that reference foundation values.

feat: resolve the base value behind variables

---

README.md
package.json
src/client/client.ts
src/server/features/completion/completion.ts
src/server/server.ts
src/server/settings.ts
src/test/helpers.ts

VS Code has built-in settings for filtering out these things
(and more) on the front-end:
- `editor.suggest.showConstants`
- `editor.suggest.showFunctions`
- `editor.suggest.showMethods`
- `editor.suggest.showVariables`

chore: remove redundant custom settings

---

e2e/src/suite/hover/hover.test.ts
fixtures/e2e/completion/use-use/_first.scss
fixtures/e2e/completion/use-use/_second.scss
fixtures/e2e/completion/use-use/main.scss
fixtures/e2e/hover/_config.scss
fixtures/e2e/hover/collision.scss
package.json
server/src/features/completion/completion.ts
server/src/features/diagnostics/diagnostics.ts
server/src/features/go-definition/go-definition.ts
server/src/features/hover/hover.ts
server/src/features/signature-help/signature-help.ts
server/src/parser/scss-document.ts
server/src/parser/scss-symbol.ts
server/src/server.ts

Suggestions and such should stick to the compiler rules for availability.
Things that are used, and not forwarded, is not available to dependants.
Fixes https://github.com/wkillerud/vscode-scss/issues/61
---
Only return hover info for built-in if there's no other content
Fixes #63 
---
Don't suggest SassDoc annotations on space (very noisy when writing docs).

Don't follow more than the first use, and don't overwrite hover info with built-in

---

package-lock.json
package.json
server/src/test/utils/sassdoc.spec.ts
server/src/utils/sassdoc.ts

Adds:
- name, if different from the actual name
- group
- access, but only if private (the value is public by default)
- todo

Add missing SassDoc attributes to tooltips

---

.github/workflows/release.yml
.husky/commit-msg
CONTRIBUTING.md
commitlint.config.js
package-lock.json
package.json
release.config.cjs

- Configure `semantic-release-vsce` to publish to VS Marketplace and Open VSX
- Add `commitlint` as a Git hook
- Mention conventional commits in the contributing docs

chore: set up automatic publishing

---

e2e/src/suite/completion/completion.test.ts
server/src/features/completion/variable-completion.ts

fix: no longer omit the $ in variable completions for Svelte

---

e2e/src/suite/completion/completion.test.ts
e2e/src/suite/completion/helper.ts
fixtures/e2e/completion/AppButton.astro
fixtures/e2e/completion/AppButton.svelte
fixtures/e2e/completion/AppButton.vue
fixtures/e2e/completion/main.scss
server/src/features/completion/completion.ts
web/src/suite/completion.test.ts

Fixes the bug mentioned in https://github.com/wkillerud/vscode-scss/issues/97#issuecomment-1902087271
I already do this same exercise for [regular function completions](https://github.com/wkillerud/vscode-scss/blob/beee6662455a39d0029279ebf438d828ca686644/server/src/features/completion/function-completion.ts#L57), [mixin completions](https://github.com/wkillerud/vscode-scss/blob/beee6662455a39d0029279ebf438d828ca686644/server/src/features/completion/mixin-completion.ts#L61) and [variable completions](https://github.com/wkillerud/vscode-scss/blob/beee6662455a39d0029279ebf438d828ca686644/server/src/features/completion/variable-completion.ts#L92). Forgot about it for completions for Sass built-ins.

fix: avoid inserting double dots for built-ins like `math.floor` in Svelte, Vue and Astro

---

packages/language-server/README.md

Try to visualize how vscode-css-languageserver and some-sass-language-server complement each other.

docs: table of capabilities

---

packages/language-server/README.md
packages/language-server/bin/some-sass-language-server
packages/language-server/src/server.ts

Add `--debug` flag to run the development build.
The development build can help give more context in case of a crash.
Also fixes a crash during initialize if there were no settings for `somesass`.

feat: debug flag

---

packages/language-services/src/features/__tests__/find-document-links.test.ts
packages/language-services/src/features/do-complete.ts
vscode-extension/test/fixtures/completion/circular.scss
vscode-extension/test/fixtures/completion/main.scss
vscode-extension/test/fixtures/definition/circular.scss
vscode-extension/test/fixtures/definition/main.scss
vscode-extension/test/fixtures/diagnostics/circular.scss
vscode-extension/test/fixtures/diagnostics/main.scss
vscode-extension/test/fixtures/hover/circular.scss
vscode-extension/test/fixtures/hover/main.scss
vscode-extension/test/fixtures/references/circular.scss
vscode-extension/test/fixtures/references/one.scss

Removes the fallback that calls vscode-css-languageservice. Duplicates aren't combined in the client.
Maybe this could be a setting in the future, in case folks want one language server to handle all the things.

fix: avoid duplicate suggestions for CSS

---

packages/language-services/src/features/find-colors.ts
packages/language-services/src/language-feature.ts
packages/language-services/src/language-services-types.ts

Avoid getting stuck processing color decorators for large documents.
Fixes #164

fix: look up the editor limit for color decorators

---

package.json
packages/language-services/src/features/__tests__/do-complete-modules.test.ts
packages/language-services/src/features/do-complete.ts
packages/language-services/src/language-feature.ts

- Hides private symbols prefixed with `-`
- Fix a regression where all `@use`d modules would be suggested.
- Fix the filter text so functions get suggested if `@use`d with a wildcard alias.

fix: regressions for namespaced completions

---

packages/language-server/src/node-file-system.ts

fix: don't crash on ENOENT when looking up realPath

---

packages/language-server/src/server.ts
packages/language-services/src/features/__tests__/do-complete-at-rules.test.ts
packages/language-services/src/features/__tests__/do-complete-interpolation.test.ts
packages/language-services/src/features/__tests__/do-complete-modules.test.ts
packages/language-services/src/features/__tests__/do-complete.test.ts
packages/language-services/src/features/do-complete.ts
packages/language-services/src/language-feature.ts

Fixes most issues mentioned in #186, and a bonus:
- Add completions after [`@warn`](https://sass-lang.com/documentation/at-rules/warn/), [`@error`](https://sass-lang.com/documentation/at-rules/error/) and [`@debug`](https://sass-lang.com/documentation/at-rules/debug/)
- Add completions when using interpolation as part of a class selector.
- Suggest symbols from the `@use` document also when it has `@forward` that include symbols.

fix: code completion bugs

---

packages/language-services/src/features/__tests__/do-complete-interpolation.test.ts
packages/language-services/src/features/__tests__/do-complete.test.ts
packages/language-services/src/features/do-complete.ts

The completion context didn't account for these cases. In the case of mixins, if the line had an `@include`, it would only suggest mixins. With this change you should see functions and variables pop up in this example.
```scss
@include test.hello(test.);
```
Similarly, the completion context didn't detect string interpolation properly when inside a parameter list for a function. After this change you should start seeing variables and function suggested in this example.
```scss
$test: #{test.selector(test.)};
```

fix: suggest variables and symbols as parameters in string interpolation and mixin includes

---

packages/language-services/src/features/__tests__/do-complete-modules.test.ts
packages/language-services/src/features/do-complete.ts

Fixes the issue mentioned here 
https://github.com/wkillerud/some-sass/issues/190#issuecomment-2273540226

fix: suggest from forwarded sass built-ins

---

packages/language-services/src/features/__tests__/do-complete-modules.test.ts
packages/language-services/src/features/__tests__/do-complete.test.ts
packages/language-services/src/features/do-complete.ts

fix: add prefix support to forwarded sass built-ins

---

packages/language-server/src/server.ts
packages/language-services/src/features/__tests__/do-complete-node-modules.test.ts
vscode-extension/test/web/suite/completion.test.js

Somehow this fell through the cracks. E2E tests only use the default settings, and tests at the lower levels didn't catch the missing link in the server.
With this change the [code suggestion settings](https://wkillerud.github.io/some-sass/user-guide/settings.html#code-suggestion) will work again.
Fixes #203

fix: apply completion settings

---

packages/language-services/src/features/__tests__/do-complete-modules.test.ts
packages/language-services/src/features/do-complete.ts
packages/vscode-css-languageservice/src/cssLanguageTypes.ts
packages/vscode-css-languageservice/src/services/scssCompletion.ts

With the limitation that VSCode will still suggest them (at time of writing) because of the built-in SCSS language feature.
We could perhaps upstream a similar setting to [microsoft/vscode-css-languageservice](https://github.com/microsoft/vscode-css-languageservice/)
Fixes #208

fix: exclude sass globals if suggestFromUseOnly

---

docs/src/SUMMARY.md
docs/src/contributing/development-environment.md
docs/src/contributing/testing-other-editors.md
docs/src/language-server/configure-a-client.md
docs/src/language-server/existing-clients.md
docs/src/language-server/getting-started.md
docs/src/language-server/helix.md
packages/language-server/src/server.ts
packages/language-server/src/settings.ts
packages/language-services/src/features/do-complete.ts
packages/language-services/src/language-feature.ts
packages/language-services/src/language-services-types.ts

Testing in Helix, which uses a different grammar for SCSS than Code, revealed a few annoying nits with completions.
This version adds two new settings that can be useful for maintainers of language clients and editor configurations:
- `somesass.completions.afterModule`
- `somesass.completions.beforeVariable`
afterModule lets you control whether or not to insert a `.` when accepting a suggestion from modules. If you see for instance `module..$variable` then try setting `afterModule` to an empty string.
beforeVariable is for non-module variables. If you see double dollars (`$$variable`) then set this to the empty string.

feat: add two settings to tweak completions in other editors

---

packages/language-server/src/server.ts
packages/language-services/src/features/do-complete.ts

`module..mixin` was a thing in indented, no more.

fix: remove extra dot for mixins and methods after modules in indented

---

docs/src/language-server/configure-a-client.md
docs/src/language-server/helix.md
packages/language-server/README.md
packages/language-server/src/server.ts
packages/language-server/src/settings.ts
packages/language-services/src/features/__tests__/do-complete-embedded.test.ts
packages/language-services/src/features/__tests__/do-complete-modules.test.ts
packages/language-services/src/features/__tests__/do-complete-placeholders.test.ts
packages/language-services/src/features/__tests__/do-complete-sassdoc.test.ts
packages/language-services/src/features/do-complete.ts
packages/language-services/src/features/do-diagnostics.ts
packages/language-services/src/language-feature.ts
packages/language-services/src/language-services-types.ts
packages/language-services/src/utils/test-helpers.ts
vscode-extension/test/e2e/defaults-scss/completion.test.js
vscode-extension/test/web/suite/completion.test.js

The edge cases in different editors with regards to word boundaries has been too high (even for syntaxes in the same editor).
~~Since perhaps not all clients support it, adopting this without checking for clientCapabilities would be a breaking change. We keep the existing behavior for backwards compatibility.~~ Nevermind, I'm looking at it wrong. From 3.16 is the new InsertReplaceEdit. [`textEdit` is as old as the spec](https://github.com/Microsoft/language-server-protocol/blob/main/versions/protocol-1-x.md#completion-request).
TODO:
Replaces #231 
For #230

fix: use textEdit for completion items insertion

---

packages/language-services/src/features/find-colors.ts

fix: no duplicate decorators if suggestAllFromOpenDocument is true

---

packages/language-services/src/features/__tests__/do-signature-help.test.ts
packages/language-services/src/features/do-signature-help.ts
vscode-extension/rspack.browser.config.js
vscode-extension/rspack.node.config.js

https://github.com/user-attachments/assets/ee15ebec-bde8-44a6-b807-85fc08121a94

fix: signature help no longer flickers on and off

---

packages/language-server/src/server.ts

Fixes a crash where configuration couldn't be found for language ID `vue`.

fix: deprecation diagnostics in vue, astro, svelte

---

packages/vscode-css-languageservice/src/parser/cssParser.ts
packages/vscode-css-languageservice/src/test/sass/parserIndented.test.ts

Fixes a complaint from the parser about an unknown at-rule.
Fixes #316

fix: handle newlines after charset in indented

---

vscode-extension/languages/sass.tmLanguage.json

Update indented grammar to handle indented comments.
Fixes #250

fix: indented comment syntax highlighting
