src/server/server.ts

Scanner didn't update existing files naturally. We also didn't remove deleted files. Both now fixed.

fix: update files on branch change

---

package-lock.json
package.json
src/server/features/completion/color-completion.ts
src/server/features/completion/variable-completion.ts

VS Code won't preview them all, but at least acknowledge they're colors.

fix: read modern color formats in completions

---

client/package-lock.json
package-lock.json
server/package-lock.json
server/package.json
server/src/parser/parser.ts

Dynamic import of the sassdoc parser only works within this project.

Dependencies

---

e2e/src/suite/completion/completion.test.ts
package-lock.json
package.json
server/src/features/completion/completion-context.ts
server/src/features/completion/completion-utils.ts
server/src/features/completion/completion.ts
server/src/features/completion/function-completion.ts
server/src/features/completion/import-completion.ts
server/src/features/completion/mixin-completion.ts
server/src/features/completion/placeholder-completion.ts
server/src/features/completion/variable-completion.ts
server/src/features/hover/hover.ts
server/src/features/sass-built-in-modules.ts
server/src/features/signature-help/signature-help.ts
server/src/parser/parser.ts
server/src/scanner.ts
server/src/storage.ts
server/src/test/utils/embedded.spec.ts
server/src/test/utils/string.spec.ts
server/src/utils/embedded.ts
server/src/utils/sassdoc.ts
server/src/utils/string.ts

- Some refactoring to clean things up and avoid unnecessary work
- Use same presentation in completions as hover

Use same presentation in completions as hover

---

.eslintrc.json
.github/workflows/release.yml
package-lock.json
package.json
release.config.cjs

Manual publishing to Marketplace to begin with, but the intent is to publish on merge

chore: set up semantic-release

---

client/package-lock.json
client/package.json
server/package-lock.json
server/package.json
server/src/file-system-provider.ts
server/src/parser/node.ts
webpack.config.js

Update webpack config to fix an issue with `process/browser` resolve from `vscode-uri` now that it's seemingly ESM.

fix: use latest css-languageservice

---

.github/workflows/pull_request.yml
.vscode/launch.json
.vscode/settings.json
.vscode/tasks.json
CONTRIBUTING.md
client/src/browser-client.ts
client/src/client.ts
client/src/node-client.ts
fixtures/e2e/.vscode/settings.json
package.json
server/src/file-system-provider.ts
server/src/server.ts
web/package-lock.json
web/package.json
web/patches/@vscode+test-web+0.0.49.patch
web/src/runTest.ts
web/src/suite/completion.test.ts
web/src/suite/definitions.test.ts
web/src/suite/example.test.ts
web/src/suite/hover.test.ts
web/src/suite/index.ts
web/src/suite/signature.test.ts
web/src/suite/util.ts
web/tsconfig.json
web/tsconfig.runtest.json
webpack.test-web.config.js

Awaiting feedback on PR upstream, but let's try this thing on CI

test: update to latest test-web, patch for search provider

---

client/package-lock.json
client/package.json
e2e/package-lock.json
e2e/package.json
server/package-lock.json
server/package.json

Includes these changes:
- https://github.com/microsoft/vscode-languageserver-node/milestone/46?closed=1
- https://github.com/microsoft/vscode-languageserver-node/milestone/61?closed=1

fix: update language client and server to v9

---

client/package-lock.json
client/package.json
renovate.json
server/package-lock.json
server/package.json
server/src/test/parser/cssNodes.spec.ts

Tests should catch whether we need to sync [NodeType](https://github.com/wkillerud/vscode-scss/blob/047d2eedf525fbfccf0174bd172f4db2375795b8/server/src/parser/node.ts#L5)

chore: let renovate bump css-languageservices

---

.github/workflows/publish_docs.yml
.github/workflows/release.yml
.gitignore
docs/book.toml
docs/src/README.md
docs/src/SUMMARY.md

Let's see about using it as a docsite on GitHub Pages

docs: test mdbook

---

package-lock.json
packages/vscode-css-languageservice/src/parser/cssParser.ts
packages/vscode-css-languageservice/src/parser/scssParser.ts
packages/vscode-css-languageservice/src/test/scss/parser.test.ts
vscode-extension/package.json

https://github.com/Microsoft/vscode-css-languageservice/compare/v6.2.13...v6.2.14
Closes #146

fix: update vscode-css-languageservice to 6.2.14

---

packages/language-services/src/features/__tests__/do-complete-modules.test.ts
packages/language-services/src/features/do-complete.ts

fix: off-by-one for the start of namespace traversal

---

package-lock.json
packages/vscode-css-languageservice/src/data/webCustomData.ts
packages/vscode-css-languageservice/src/parser/cssNodes.ts
packages/vscode-css-languageservice/src/parser/scssParser.ts
packages/vscode-css-languageservice/src/services/cssNavigation.ts
packages/vscode-css-languageservice/src/services/scssNavigation.ts
packages/vscode-css-languageservice/src/test/scss/scssNavigation.test.ts
packages/vscode-css-languageservice/src/test/testUtil/fsProvider.ts
packages/vscode-css-languageservice/src/utils/strings.ts
packages/vscode-css-languageservice/test/linksTestFixtures/node_modules/sass-true/package.json
vscode-extension/package.json

https://nodejs.org/api/packages.html#conditional-exports
Fixes #184

fix: support declaring exports without path 

---

vscode-extension/README.md

See issue [#187](https://github.com/wkillerud/some-sass/issues/187).
Please let me know if everything is fine.

docs: fix readme setting to suggestFromUseOnly

---

docs/src/user-guide/settings.md
packages/language-server/src/server.ts
packages/language-server/src/settings.ts
packages/language-services/src/features/do-rename.ts
packages/language-services/src/language-services-types.ts
packages/vscode-css-languageservice/src/cssLanguageService.ts
packages/vscode-css-languageservice/src/cssLanguageTypes.ts
packages/vscode-css-languageservice/src/services/cssNavigation.ts
packages/vscode-css-languageservice/src/test/scss/scssNavigation.test.ts
vscode-extension/package.json
vscode-extension/src/settings.ts

feat: add support for loadPaths via a setting

---

package-lock.json
packages/language-server/src/server.ts
vscode-extension/package.json

Fixes an issue mentioned in #207

fix: apply loadPaths in onDidChangeConfiguration

---

packages/language-server/src/server.ts
packages/language-services/src/features/__tests__/do-diagnostics.test.ts
packages/language-services/src/language-feature.ts
packages/language-services/src/language-services-types.ts
packages/language-services/src/language-services.ts
packages/vscode-css-languageservice/src/services/cssValidation.ts

fix: bugs with unknown at-rules and customData

---

package-lock.json
package.json
packages/vscode-css-languageservice/docs/customData.md
packages/vscode-css-languageservice/docs/customData.schema.json
packages/vscode-css-languageservice/package.json
packages/vscode-css-languageservice/src/cssLanguageTypes.ts
packages/vscode-css-languageservice/src/data/webCustomData.ts
packages/vscode-css-languageservice/src/languageFacts/colors.ts
packages/vscode-css-languageservice/src/languageFacts/entry.ts
packages/vscode-css-languageservice/src/parser/cssNodes.ts
packages/vscode-css-languageservice/src/parser/cssParser.ts
packages/vscode-css-languageservice/src/parser/cssScanner.ts
packages/vscode-css-languageservice/src/services/cssNavigation.ts
packages/vscode-css-languageservice/src/services/selectorPrinting.ts
packages/vscode-css-languageservice/src/test/css/completion.test.ts
packages/vscode-css-languageservice/src/test/css/hover.test.ts
packages/vscode-css-languageservice/src/test/css/languageFacts.test.ts
packages/vscode-css-languageservice/src/test/css/navigation.test.ts
packages/vscode-css-languageservice/src/test/css/nodes.test.ts
packages/vscode-css-languageservice/src/test/css/parser.test.ts
packages/vscode-css-languageservice/src/test/sass/languageFacts.test.ts
packages/vscode-css-languageservice/src/test/sass/sassHover.test.ts
vscode-extension/package.json

Closes #298, closes #297, closes #296, closes #295

April updates

---

.github/workflows/pull_request.yml
.github/workflows/release-vscode.yml
.github/workflows/release.yml
nx.json
package.json
packages/language-server/package.json
packages/language-services/package.json
packages/vscode-css-languageservice/package.json
vscode-extension/package.json

Get a clean non-dev dist before publish

chore: reconfigure prod build and CI

---

package-lock.json
packages/vscode-css-languageservice/docs/customData.schema.json
packages/vscode-css-languageservice/package.json
packages/vscode-css-languageservice/src/cssLanguageTypes.ts
packages/vscode-css-languageservice/src/data/webCustomData.ts
packages/vscode-css-languageservice/src/languageFacts/colors.ts
packages/vscode-css-languageservice/src/services/cssCompletion.ts
packages/vscode-css-languageservice/src/services/cssNavigation.ts
packages/vscode-css-languageservice/src/test/css/completion.test.ts
packages/vscode-css-languageservice/src/test/css/languageFacts.test.ts
packages/vscode-css-languageservice/src/test/css/navigation.test.ts
packages/vscode-css-languageservice/src/tsconfig.esm.json
vscode-extension/package.json

Merge updates from upstream
https://github.com/Microsoft/vscode-css-languageservice/compare/v6.3.5...v6.3.7

feat: add support for oklab and oklch color functions

---

packages/language-services/src/features/__tests__/do-complete.test.ts
packages/language-services/src/features/__tests__/find-references.test.ts
packages/language-services/src/features/do-complete.ts
packages/vscode-css-languageservice/src/test/sass/parser.test.ts
packages/vscode-css-languageservice/src/test/sass/parserIndented.test.ts

fix: completions for values forwarded with prefix and show

---

package-lock.json
packages/vscode-css-languageservice/package.json
packages/vscode-css-languageservice/src/data/webCustomData.ts
packages/vscode-css-languageservice/src/services/cssCompletion.ts

fix: update web data, value completion for white-space property
